### ISSUE TITLE
Clicking "Awakening Levels" in "Weapons" tab leads to blank screen

### ISSUE THREAD

**Issue by beetalogist** [3nvy/wayfinder-save-editor#21]
Only fix is to close and re-open the program
![image](https://github.com/user-attachments/assets/b086c9df-0c50-4163-bfd3-f84d0470d894)

**Comment by 3nvy** [comment]
Weird, it works fine for me. It could be some weapon Im not accounting for with a different structure 🤔 

Would you be able to share your save so I can debug the error?

**Comment by beetalogist** [comment]
Here it is
[WayfinderSave_7.zip](https://github.com/user-attachments/files/17532297/WayfinderSave_7.zip)

**Comment by 3nvy** [comment]
Ok, found the issue. Its trying to process the awakening level of a new weapon that I havent mapped on the save editor yet. Im currently already mapping the new echos and weapons, so hopefully should have a fix tomorrow.

Ill also add some conditions so it doesnt break in the future because of this 👍

**Comment by 3nvy** [comment]
This is now fixed on the latest release https://github.com/3nvy/wayfinder-save-editor/releases/tag/2.6.0
